services:
  - type: web
    name: scritodon-backend
    env: python
    plan: free
    sourceDir: backend
    buildCommand: |
      export CARGO_HOME=/tmp/cargo
      export RUSTUP_HOME=/tmp/rustup
      export PIP_NO_CACHE_DIR=1
      mkdir -p $CARGO_HOME $RUSTUP_HOME
      pip install --upgrade pip
      pip install --no-cache-dir --prefer-binary -r requirements.txt || pip install --no-cache-dir --prefer-binary -r requirements-stable.txt
    startCommand: python start_render.py
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./scritodon.db
      - key: OPENROUTER_API_KEY
        sync: false
      - key: CARGO_HOME
        value: /tmp/cargo
      - key: RUSTUP_HOME
        value: /tmp/rustup
      - key: PIP_NO_CACHE_DIR
        value: 1
    pythonVersion: 3.11.7 