services:
  - type: web
    name: scritodon-backend
    env: python
    plan: free
    sourceDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./scritodon.db
      - key: OPENROUTER_API_KEY
        sync: false
    pythonVersion: 3.9.18 